source = $HOME/.config/hypr/themes/catppuccin-latte.conf

$accent = $mauve
$font = SpaceMono Nerd Font

general {
    hide_cursor = true
}

background {
    monitor =
    color = $base
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = $text
    font_family = $font
    font_size = 72
    position = 0, 120
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 52
    position = 0, -30
    outline_thickness = 1
    rounding = 0
    dots_center = true
    dots_rounding = 0
    hide_input = true
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    outer_color = $accent
    inner_color = $surface0
    font_color = $text
    check_color = $green
    fail_color = $red
    halign = center
    valign = center
}
