add_newline = true

format = """
$cmd_duration[](none)$directory$git_branch $fill [](none)$battery$memory_usage$time
$character"""

right_format = """
$python
"""

[character]
success_symbol = "[󰁃 ](none)"
error_symbol = "[󰁜 ](none)"

[git_branch]
symbol = "󰘬"
truncation_length = 4
truncation_symbol = ""
format = "[ $symbol $branch(:$remote_branch) ](none)"

[directory]
home_symbol = "  "
read_only = "  "
truncation_length = 6
truncation_symbol = "../"
format = "[ $path ](none)"

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = "  "
"Pictures" = "  "
"Videos" = "  "

[cmd_duration]
min_time = 0
format = "[  $duration ](none)"

[fill]
symbol = " "
style = "none"

[python]
format = "[ $virtualenv ${version} ](none)"

[battery]
format = "[ $symbol $percentage ](none)"

[[battery.display]]
threshold = 20
style = "none"

[memory_usage]
disabled = false
threshold = -1
format = "[ 󰍛 $ram  $swap ](none)"

[time]
disabled = false
time_format = "%T"
format = "[  $time ](none)"
